author: 
  name: "Andrés Jorge Giménez Muñoz"
  email: "agimenezmunoz@educa.madrid.com" 
  watermark: "Profesor: Andrés"
school:
  name: "IES Humanes"
  logo: logo-ies_humanes.png
exam-info:
   academic-period: "Curso 2026/2027"
show-solutions: true
