version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - academic
  - align
  - alpha
  - approx
  - arccos
  - arctan
  - arrow
  - augment
  - author
  - Barrow
  - Bayes
  - bicuadradas
  - binomial
  - black
  - blue
  - Bolzano
  - bottom
  - canvas
  - center
  - cetz
  - circle
  - clarification
  - clarifications
  - colbreak
  - columns
  - community
  - complanarios
  - derivabilidad
  - derivable
  - dispatch
  - draw
  - Dyslexic
  - equiv
  - exam
  - examples
  - Fernán
  - fill
  - find
  - font
  - forall
  - github
  - gutter
  - IES
  - iname
  - inecuaciones
  - Inecuaciones
  - infinity
  - inter
  - Laplace
  - length
  - line
  - math
  - month
  - muestral
  - none
  - north
  - octaédrico
  - overline
  - padding
  - pagebreak
  - pages
  - plot
  - print
  - question
  - questions
  - right
  - Ruffini
  - school
  - separator
  - setup
  - space
  - spacex
  - stretch
  - stroke
  - student
  - StudentData
  - style
  - subject
  - subquestion
  - subset
  - Thales
  - theta
  - typst
  - union
  - watermark
  - while
  - white
  - width
  - year
ignoreWords: []
import: []
language: es-ES,en-UK
