version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - es
  - en
  - custom-dictionary
words:
  - cetz
  - colbreak
  - forall
  - hline
  - pagebreak
  - subquestion
  - typst
ignoreWords: []
import: []
